/**
 * ESP32 Platform - Audio HAL Implementation
 *
 * Uses ESP32 I2S driver with ES8311 codec (DAC+ADC) and optional ES7210 ADC.
 * MCLK is generated by the I2S peripheral via APLL (not LEDC).
 * Reference: Waveshare ESP32-S3-Touch-AMOLED-1.75 example 08_ES8311
 */

#ifdef PLATFORM_ESP32

#include "../../hal/audio_hal.h"
#include "pin_config.h"
#include "../../src/config.h"
#include "es7210.h"
#include <Arduino.h>
#include <driver/i2s.h>
#include <driver/gpio.h>
#include <Wire.h>

// Audio state
static bool audioInitialized = false;
static bool audioRunning = false;
static bool es7210Present = false;
static uint8_t currentVolume = 90;

// I2S configuration
static const i2s_port_t I2S_PORT = I2S_NUM_0;

// MCLK = sample_rate * 256 = 16000 * 256 = 4096000
// Using 12.288MHz as it's a standard audio clock and in the ES8311 coeff table
static const uint32_t MCLK_FREQ = 12288000;

// ES8311 codec I2C address (7-bit: CE pin low = 0x18)
static const uint8_t ES8311_I2C_ADDR = 0x18;

// ES8311 Register Map
#define ES8311_RESET_REG00        0x00
#define ES8311_CLK_MANAGER_REG01  0x01
#define ES8311_CLK_MANAGER_REG02  0x02
#define ES8311_CLK_MANAGER_REG03  0x03
#define ES8311_CLK_MANAGER_REG04  0x04
#define ES8311_CLK_MANAGER_REG05  0x05
#define ES8311_CLK_MANAGER_REG06  0x06
#define ES8311_CLK_MANAGER_REG07  0x07
#define ES8311_CLK_MANAGER_REG08  0x08
#define ES8311_SDPIN_REG09        0x09
#define ES8311_SDPOUT_REG0A       0x0A
#define ES8311_SYSTEM_REG0B       0x0B
#define ES8311_SYSTEM_REG0C       0x0C
#define ES8311_SYSTEM_REG0D       0x0D
#define ES8311_SYSTEM_REG0E       0x0E
#define ES8311_SYSTEM_REG0F       0x0F
#define ES8311_SYSTEM_REG10       0x10
#define ES8311_SYSTEM_REG11       0x11
#define ES8311_SYSTEM_REG12       0x12
#define ES8311_SYSTEM_REG13       0x13
#define ES8311_SYSTEM_REG14       0x14
#define ES8311_ADC_REG15          0x15
#define ES8311_ADC_REG16          0x16
#define ES8311_ADC_REG17          0x17
#define ES8311_ADC_REG1C          0x1C
#define ES8311_DAC_REG31          0x31
#define ES8311_DAC_REG32          0x32
#define ES8311_DAC_REG37          0x37
#define ES8311_GPIO_REG44         0x44
#define ES8311_CHD1_REGFD         0xFD
#define ES8311_CHD2_REGFE         0xFE
#define ES8311_CHVER_REGFF        0xFF

static bool es8311_write_reg(uint8_t reg, uint8_t value) {
    Wire.beginTransmission(ES8311_I2C_ADDR);
    Wire.write(reg);
    Wire.write(value);
    bool ok = Wire.endTransmission() == 0;
    if (!ok) {
        Serial.printf("ES8311: write reg 0x%02X = 0x%02X FAILED\n", reg, value);
    }
    return ok;
}

static uint8_t es8311_read_reg(uint8_t reg) {
    Wire.beginTransmission(ES8311_I2C_ADDR);
    Wire.write(reg);
    Wire.endTransmission(false);
    Wire.requestFrom((uint8_t)ES8311_I2C_ADDR, (uint8_t)1);
    if (Wire.available()) {
        return Wire.read();
    }
    return 0xFF;
}

// Read-modify-write helper
static bool es8311_update_reg(uint8_t reg, uint8_t mask, uint8_t value) {
    uint8_t old = es8311_read_reg(reg);
    uint8_t updated = (old & ~mask) | (value & mask);
    return es8311_write_reg(reg, updated);
}

static void es8311_dump_regs(void) {
    Serial.println("ES8311 register dump:");
    for (int reg = 0; reg <= 0x45; reg++) {
        uint8_t val = es8311_read_reg(reg);
        Serial.printf("  REG[0x%02X] = 0x%02X\n", reg, val);
    }
    // Chip ID
    Serial.printf("  CHIP_ID1[0xFD] = 0x%02X\n", es8311_read_reg(0xFD));
    Serial.printf("  CHIP_ID2[0xFE] = 0x%02X\n", es8311_read_reg(0xFE));
    Serial.printf("  VERSION[0xFF] = 0x%02X\n", es8311_read_reg(0xFF));
}

// Initialize PA (Power Amplifier) enable GPIO
static void init_pa_en(void) {
    gpio_set_direction((gpio_num_t)PA_EN, GPIO_MODE_OUTPUT);
    gpio_set_level((gpio_num_t)PA_EN, 0);
    Serial.printf("ESP32: PA_EN initialized on GPIO%d (disabled)\n", PA_EN);
}

static void set_pa_enabled(bool enabled) {
    gpio_set_level((gpio_num_t)PA_EN, enabled ? 1 : 0);
    Serial.printf("ESP32: PA %s\n", enabled ? "enabled" : "disabled");
}

// Official coefficient table entry for MCLK=12.288MHz, rate=16kHz
// From Espressif es8311.c: {12288000, 16000, 0x03, 0x00, 0x01, 0x01, 0x00, 0x00, 0xff, 0x04, 0x10, 0x10}
static const struct {
    uint8_t pre_div;    // 0x03
    uint8_t pre_multi;  // 0x00
    uint8_t adc_div;    // 0x01
    uint8_t dac_div;    // 0x01
    uint8_t fs_mode;    // 0x00
    uint8_t lrck_h;     // 0x00
    uint8_t lrck_l;     // 0xFF
    uint8_t bclk_div;   // 0x04
    uint8_t adc_osr;    // 0x10
    uint8_t dac_osr;    // 0x10
} coeff = {0x03, 0x00, 0x01, 0x01, 0x00, 0x00, 0xFF, 0x04, 0x10, 0x10};

// Initialize ES8311 - follows official Espressif driver sequence exactly
static bool es8311_init_codec(void) {
    Serial.println("ES8311: Initializing codec...");

    // Check presence
    Wire.beginTransmission(ES8311_I2C_ADDR);
    if (Wire.endTransmission() != 0) {
        Serial.println("ES8311: NOT FOUND at 0x18!");
        return false;
    }

    // Read chip ID to verify it's actually an ES8311
    uint8_t id1 = es8311_read_reg(ES8311_CHD1_REGFD);
    uint8_t id2 = es8311_read_reg(ES8311_CHD2_REGFE);
    uint8_t ver = es8311_read_reg(ES8311_CHVER_REGFF);
    Serial.printf("ES8311: Chip ID = 0x%02X 0x%02X, Version = 0x%02X\n", id1, id2, ver);

    if (id1 != 0x83 || id2 != 0x11) {
        Serial.printf("ES8311: WARNING - unexpected chip ID (expected 0x83 0x11, got 0x%02X 0x%02X)\n", id1, id2);
        Serial.println("ES8311: This may indicate I2C address conflict with another device");
    }

    // Reset
    es8311_write_reg(ES8311_RESET_REG00, 0x1F);
    delay(20);
    es8311_write_reg(ES8311_RESET_REG00, 0x00);
    es8311_write_reg(ES8311_RESET_REG00, 0x80);

    // Clock source: MCLK from MCLK pin, enable all clocks
    es8311_write_reg(ES8311_CLK_MANAGER_REG01, 0x3F);

    // Clock dividers (read-modify-write per official driver)
    // REG02: preserve bits [2:0], set pre_div and pre_multi
    es8311_update_reg(ES8311_CLK_MANAGER_REG02, 0xF8,
        ((coeff.pre_div - 1) << 5) | (coeff.pre_multi << 3));

    // REG03: fs_mode and adc_osr (full write OK)
    es8311_write_reg(ES8311_CLK_MANAGER_REG03,
        (coeff.fs_mode << 6) | coeff.adc_osr);

    // REG04: dac_osr
    es8311_write_reg(ES8311_CLK_MANAGER_REG04, coeff.dac_osr);

    // REG05: adc_div and dac_div
    es8311_write_reg(ES8311_CLK_MANAGER_REG05,
        ((coeff.adc_div - 1) << 4) | (coeff.dac_div - 1));

    // REG06: preserve bits [7:5] (BCLK invert etc), set bclk_div in [4:0]
    es8311_update_reg(ES8311_CLK_MANAGER_REG06, 0x1F, coeff.bclk_div - 1);

    // REG07: preserve bits [7:6], set lrck_h in [5:0]
    es8311_update_reg(ES8311_CLK_MANAGER_REG07, 0x3F, coeff.lrck_h);

    // REG08: lrck_l
    es8311_write_reg(ES8311_CLK_MANAGER_REG08, coeff.lrck_l);

    // SDP format: I2S slave, 16-bit
    // REG00: ensure slave mode (bit 6 = 0)
    es8311_update_reg(ES8311_RESET_REG00, 0x40, 0x00);

    // REG09 (SDP In / DAC): 16-bit I2S
    es8311_write_reg(ES8311_SDPIN_REG09, (3 << 2));

    // Disable REG0A (SDP Out / ADC) to tristate the DOUT pin!
    // If ES8311 ADC is active, it fights the ES7210 on GPIO 10.
    es8311_write_reg(ES8311_SDPOUT_REG0A, 0x00);

    // Power up analog circuitry (DAC only)
    es8311_write_reg(ES8311_SYSTEM_REG0D, 0x01);
    es8311_write_reg(ES8311_SYSTEM_REG0E, 0x02);
    es8311_write_reg(ES8311_SYSTEM_REG12, 0x00);
    es8311_write_reg(ES8311_SYSTEM_REG13, 0x10);

    // Disable ADC config to ensure no data is driven
    es8311_write_reg(ES8311_ADC_REG1C, 0x00);
    es8311_write_reg(ES8311_SYSTEM_REG14, 0x00);  // Disable analog MIC
    es8311_write_reg(ES8311_ADC_REG17, 0x00);     // ADC gain
    es8311_write_reg(ES8311_ADC_REG16, 0x00);     // Mic gain

    // DAC config
    es8311_write_reg(ES8311_DAC_REG37, 0x08);

    // Set volume
    uint8_t vol = (currentVolume == 0) ? 0 : ((currentVolume * 256 / 100) - 1);
    es8311_write_reg(ES8311_DAC_REG32, vol);

    // Unmute DAC
    es8311_write_reg(ES8311_DAC_REG31, 0x00);

    Serial.printf("ES8311: Codec initialized (vol=%d, reg32=0x%02X)\n", currentVolume, vol);
    es8311_dump_regs();
    return true;
}

void AudioHAL_init(void) {
    Serial.println("ESP32: Initializing Audio HAL...");

    init_pa_en();

    // Install I2S driver FIRST so MCLK/BCLK/LRCK are running before codec init.
    // Codecs need these clocks to enter normal operation correctly.
    i2s_config_t i2sConfig = {};
    i2sConfig.mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_TX | I2S_MODE_RX);
    i2sConfig.sample_rate = SAMPLE_RATE;
    i2sConfig.bits_per_sample = I2S_BITS_PER_SAMPLE_32BIT;  // Force 64 BCLKs/frame to satisfy ES7210 24-bit default
    i2sConfig.channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT;
    i2sConfig.communication_format = I2S_COMM_FORMAT_STAND_I2S;
    i2sConfig.intr_alloc_flags = ESP_INTR_FLAG_LEVEL1;
    i2sConfig.dma_buf_count = 8;
    i2sConfig.dma_buf_len = 256;
    i2sConfig.use_apll = true;
    i2sConfig.tx_desc_auto_clear = true;
    i2sConfig.fixed_mclk = (int)MCLK_FREQ;

    esp_err_t err = i2s_driver_install(I2S_PORT, &i2sConfig, 0, NULL);
    if (err != ESP_OK) {
        Serial.printf("ESP32: I2S driver install failed: %s\n", esp_err_to_name(err));
        return;
    }

    i2s_pin_config_t pinConfig = {};
    pinConfig.mck_io_num = MCLK_PIN;   // GPIO42 - MCLK output from I2S/APLL
    pinConfig.bck_io_num = BCLK_PIN;   // GPIO9
    pinConfig.ws_io_num = WS_PIN;      // GPIO45
    pinConfig.data_out_num = DOUT_PIN;  // GPIO8 (to ES8311 DSDIN)
    pinConfig.data_in_num = DIN_PIN;    // GPIO10 (from ES7210 ASDOUT)

    err = i2s_set_pin(I2S_PORT, &pinConfig);
    if (err != ESP_OK) {
        Serial.printf("ESP32: I2S pin config failed: %s\n", esp_err_to_name(err));
        i2s_driver_uninstall(I2S_PORT);
        return;
    }

    i2s_zero_dma_buffer(I2S_PORT);
    Serial.println("ESP32: I2S started (MCLK/BCLK/LRCK now running)");
    delay(50);

    // Now init codecs with clocks already running
    if (!es8311_init_codec()) {
        Serial.println("ESP32: Audio init failed - no ES8311 codec found");
        return;
    }

    es7210_config_t es7210_cfg = ES7210_CONFIG_DEFAULT();
    es7210_cfg.mics = ES7210_MIC_ALL;  // Enable all 4 mics (Waveshare may use MIC1/MIC3)
    es7210_cfg.gain = ES7210_GAIN_24DB;
    es7210_cfg.sample_rate = (es7210_sample_rate_t)SAMPLE_RATE;
    es7210_cfg.bits = ES7210_BITS_32;  // Match ESP32 I2S 32-bit frame width
    es7210_cfg.i2s_format = ES7210_I2S_NORMAL;
    es7210_cfg.enable_tdm = false;
    es7210_cfg.mclk_freq = MCLK_FREQ;

    if (ES7210_init(&es7210_cfg)) {
        es7210Present = true;
        Serial.println("ESP32: ES7210 microphone array initialized");
    } else {
        Serial.println("ESP32: ES7210 not found - using ES8311 ADC for mic");
    }

    audioInitialized = true;
    Serial.println("ESP32: Audio initialized successfully");
    Serial.printf("  Sample rate: %d Hz\n", SAMPLE_RATE);
    Serial.printf("  MCLK: %d Hz on GPIO%d (via I2S APLL)\n", MCLK_FREQ, MCLK_PIN);
    Serial.printf("  I2S: BCLK=%d, WS=%d, DOUT=%d, DIN=%d\n",
                  BCLK_PIN, WS_PIN, DOUT_PIN, DIN_PIN);
    Serial.printf("  PA_EN: GPIO%d\n", PA_EN);
    Serial.printf("  ES8311: 0x%02X, ES7210: 0x%02X (%s)\n",
                  ES8311_I2C_ADDR, ES7210_I2C_ADDR,
                  es7210Present ? "active" : "not found");
}

void AudioHAL_start(void) {
    if (!audioInitialized) return;

    if (es7210Present) {
        ES7210_start();
    }

    delay(50);
    set_pa_enabled(true);

    audioRunning = true;
    Serial.println("ESP32: Audio started");
}

void AudioHAL_stop(void) {
    if (!audioInitialized) return;

    set_pa_enabled(false);
    delay(10);

    if (es7210Present) {
        ES7210_stop();
    }

    es8311_write_reg(ES8311_CLK_MANAGER_REG01, 0x00);
    es8311_write_reg(ES8311_RESET_REG00, 0x00);

    audioRunning = false;
    Serial.println("ESP32: Audio stopped");
}

void AudioHAL_setVolume(uint8_t volume) {
    if (!audioInitialized) return;
    if (volume > 100) volume = 100;
    currentVolume = volume;

    uint8_t vol = (volume == 0) ? 0 : ((volume * 256 / 100) - 1);
    es8311_write_reg(ES8311_DAC_REG32, vol);

    if (volume > 0) {
        es8311_write_reg(ES8311_DAC_REG31, 0x00);
    } else {
        es8311_write_reg(ES8311_DAC_REG31, 0x60);
    }
}

uint32_t AudioHAL_readMic(int16_t* buffer, uint32_t samples) {
    if (!audioInitialized || !audioRunning || !buffer) return 0;

    size_t bytesRead = 0;
    // Read 32-bit data (2 channels)
    static int32_t i2s32Buf[AUDIO_BUFFER_SIZE * 2];
    esp_err_t err = i2s_read(I2S_PORT, i2s32Buf, samples * sizeof(int32_t) * 2,
                             &bytesRead, 100 / portTICK_PERIOD_MS);
    if (err != ESP_OK) return 0;

    uint32_t framesRead = bytesRead / (sizeof(int32_t) * 2);

    // Convert 32-bit (where 24-bit audio is MSB aligned) to 16-bit
    for (uint32_t i = 0; i < framesRead * 2; i++) {
        // Shift right by 16 to get the top 16 bits of the 32-bit word
        buffer[i] = (int16_t)(i2s32Buf[i] >> 16);
    }

    return framesRead;
}

void AudioHAL_writeSpeaker(const int16_t* buffer, uint32_t samples) {
    if (!audioInitialized || !audioRunning || !buffer) return;

    static int32_t i2s32WriteBuf[AUDIO_BUFFER_SIZE * 2];
    for (uint32_t i = 0; i < samples * 2; i++) {
        // Shift left by 16 to put our 16-bit sample into the MSBs of the 32-bit word
        i2s32WriteBuf[i] = ((int32_t)buffer[i]) << 16;
    }

    size_t bytesWritten = 0;
    i2s_write(I2S_PORT, i2s32WriteBuf, samples * sizeof(int32_t) * 2,
              &bytesWritten, 100 / portTICK_PERIOD_MS);
}

bool AudioHAL_micAvailable(void) {
    return audioInitialized && (es7210Present || true);
}

bool AudioHAL_speakerReady(void) {
    return audioInitialized;
}

#endif // PLATFORM_ESP32
