/**
 * ESP32 Platform - Audio HAL Implementation
 *
 * Single I2S0 port in full-duplex master mode (TX + RX).
 *   DOUT → ES8311 DAC (speaker), DIN ← ES7210 ADC (microphone)
 *
 * MCLK is generated by I2S0 (PLL_160M — ESP32-S3 has no APLL).
 * Reference: Waveshare ESP32-S3-Touch-AMOLED-1.75 example 08_ES8311
 */

#ifdef PLATFORM_ESP32

#include "../../hal/audio_hal.h"
#include "pin_config.h"
#include "../../src/config.h"
#include "es7210.h"
#include <Arduino.h>
#include <driver/i2s.h>
#include <driver/gpio.h>
#include <soc/i2s_periph.h>
#include <soc/gpio_reg.h>
#include <esp_rom_gpio.h>
#include <Wire.h>

// Audio state
static bool audioInitialized = false;
static bool audioRunning = false;
static bool es7210Present = false;
static uint8_t currentVolume = 90;

// 32-bit DMA buffers for I2S (codecs expect 32-bit slots per Philips I2S standard)
static int32_t i2sDmaReadBuf[AUDIO_BUFFER_SIZE * 2];
static int32_t i2sDmaWriteBuf[AUDIO_BUFFER_SIZE * 2];

// Single I2S port in full-duplex mode.
// Dual-port (TX=I2S0 master, RX=I2S1 slave) was attempted but I2S TX-only
// mode doesn't generate BCLK/WS continuously on ESP32-S3 legacy driver.
static const i2s_port_t I2S_PORT = I2S_NUM_0;

// MCLK: 12.288MHz is in the ES8311/ES7210 coefficient tables for 16kHz.
// ESP32-S3 has no APLL — MCLK is derived from PLL_160M via fractional
// divider (160MHz / 12.288MHz = 13.02x), which introduces some clock jitter.
static const uint32_t MCLK_FREQ = 12288000;

// ES8311 codec I2C address (7-bit: CE pin low = 0x18)
static const uint8_t ES8311_I2C_ADDR = 0x18;

// ES8311 Register Map
#define ES8311_RESET_REG00        0x00
#define ES8311_CLK_MANAGER_REG01  0x01
#define ES8311_CLK_MANAGER_REG02  0x02
#define ES8311_CLK_MANAGER_REG03  0x03
#define ES8311_CLK_MANAGER_REG04  0x04
#define ES8311_CLK_MANAGER_REG05  0x05
#define ES8311_CLK_MANAGER_REG06  0x06
#define ES8311_CLK_MANAGER_REG07  0x07
#define ES8311_CLK_MANAGER_REG08  0x08
#define ES8311_SDPIN_REG09        0x09
#define ES8311_SDPOUT_REG0A       0x0A
#define ES8311_SYSTEM_REG0B       0x0B
#define ES8311_SYSTEM_REG0C       0x0C
#define ES8311_SYSTEM_REG0D       0x0D
#define ES8311_SYSTEM_REG0E       0x0E
#define ES8311_SYSTEM_REG0F       0x0F
#define ES8311_SYSTEM_REG10       0x10
#define ES8311_SYSTEM_REG11       0x11
#define ES8311_SYSTEM_REG12       0x12
#define ES8311_SYSTEM_REG13       0x13
#define ES8311_SYSTEM_REG14       0x14
#define ES8311_ADC_REG15          0x15
#define ES8311_ADC_REG16          0x16
#define ES8311_ADC_REG17          0x17
#define ES8311_ADC_REG1C          0x1C
#define ES8311_DAC_REG31          0x31
#define ES8311_DAC_REG32          0x32
#define ES8311_DAC_REG37          0x37
#define ES8311_GPIO_REG44         0x44
#define ES8311_CHD1_REGFD         0xFD
#define ES8311_CHD2_REGFE         0xFE
#define ES8311_CHVER_REGFF        0xFF

static bool es8311_write_reg(uint8_t reg, uint8_t value) {
    Wire.beginTransmission(ES8311_I2C_ADDR);
    Wire.write(reg);
    Wire.write(value);
    bool ok = Wire.endTransmission() == 0;
    if (!ok) {
        Serial.printf("ES8311: write reg 0x%02X = 0x%02X FAILED\n", reg, value);
    }
    return ok;
}

static uint8_t es8311_read_reg(uint8_t reg) {
    Wire.beginTransmission(ES8311_I2C_ADDR);
    Wire.write(reg);
    Wire.endTransmission(false);
    Wire.requestFrom((uint8_t)ES8311_I2C_ADDR, (uint8_t)1);
    if (Wire.available()) {
        return Wire.read();
    }
    return 0xFF;
}

// Read-modify-write helper
static bool es8311_update_reg(uint8_t reg, uint8_t mask, uint8_t value) {
    uint8_t old = es8311_read_reg(reg);
    uint8_t updated = (old & ~mask) | (value & mask);
    return es8311_write_reg(reg, updated);
}

static void es8311_dump_regs(void) {
    Serial.println("ES8311 register dump:");
    for (int reg = 0; reg <= 0x45; reg++) {
        uint8_t val = es8311_read_reg(reg);
        Serial.printf("  REG[0x%02X] = 0x%02X\n", reg, val);
    }
    // Chip ID
    Serial.printf("  CHIP_ID1[0xFD] = 0x%02X\n", es8311_read_reg(0xFD));
    Serial.printf("  CHIP_ID2[0xFE] = 0x%02X\n", es8311_read_reg(0xFE));
    Serial.printf("  VERSION[0xFF] = 0x%02X\n", es8311_read_reg(0xFF));
}

// Initialize PA (Power Amplifier) enable GPIO
static void init_pa_en(void) {
    gpio_set_direction((gpio_num_t)PA_EN, GPIO_MODE_OUTPUT);
    gpio_set_level((gpio_num_t)PA_EN, 0);
    Serial.printf("ESP32: PA_EN initialized on GPIO%d (disabled)\n", PA_EN);
}

static void set_pa_enabled(bool enabled) {
    gpio_set_level((gpio_num_t)PA_EN, enabled ? 1 : 0);
    Serial.printf("ESP32: PA %s\n", enabled ? "enabled" : "disabled");
}

// Coefficient table entry for MCLK=12.288MHz, rate=16kHz
// From ESPHome es8311_const.h (confirmed working on this board):
//   {12288000, 16000, 0x03, 0x01, 0x01, 0x01, 0x00, 0x00, 0xff, 0x04, 0x10, 0x20}
// NOTE: Espressif esp_codec_dev has different values (pre_mult=0x00, dac_osr=0x10) — those are WRONG.
static const struct {
    uint8_t pre_div;    // 0x03
    uint8_t pre_multi;  // 0x01
    uint8_t adc_div;    // 0x01
    uint8_t dac_div;    // 0x01
    uint8_t fs_mode;    // 0x00
    uint8_t lrck_h;     // 0x00
    uint8_t lrck_l;     // 0xFF
    uint8_t bclk_div;   // 0x04
    uint8_t adc_osr;    // 0x10
    uint8_t dac_osr;    // 0x20
} coeff = {0x03, 0x01, 0x01, 0x01, 0x00, 0x00, 0xFF, 0x04, 0x10, 0x20};

// Initialize ES8311 - follows official Espressif driver sequence exactly
static bool es8311_init_codec(void) {
    Serial.println("ES8311: Initializing codec...");

    // Check presence
    Wire.beginTransmission(ES8311_I2C_ADDR);
    if (Wire.endTransmission() != 0) {
        Serial.println("ES8311: NOT FOUND at 0x18!");
        return false;
    }

    // Read chip ID to verify it's actually an ES8311
    uint8_t id1 = es8311_read_reg(ES8311_CHD1_REGFD);
    uint8_t id2 = es8311_read_reg(ES8311_CHD2_REGFE);
    uint8_t ver = es8311_read_reg(ES8311_CHVER_REGFF);
    Serial.printf("ES8311: Chip ID = 0x%02X 0x%02X, Version = 0x%02X\n", id1, id2, ver);

    if (id1 != 0x83 || id2 != 0x11) {
        Serial.printf("ES8311: WARNING - unexpected chip ID (expected 0x83 0x11, got 0x%02X 0x%02X)\n", id1, id2);
        Serial.println("ES8311: This may indicate I2C address conflict with another device");
    }

    // Reset — do NOT write 0x80 (CSM power-on) until all registers are configured.
    // ESPHome writes 0x80 as the last step; writing it early causes CSM to auto-configure
    // registers with defaults, overriding our settings.
    es8311_write_reg(ES8311_RESET_REG00, 0x1F);
    delay(20);
    es8311_write_reg(ES8311_RESET_REG00, 0x00);

    // Clock source: MCLK from MCLK pin, enable all clocks
    es8311_write_reg(ES8311_CLK_MANAGER_REG01, 0x3F);

    // Clock dividers (read-modify-write per official driver)
    // REG02: preserve bits [2:0], set pre_div and pre_multi
    es8311_update_reg(ES8311_CLK_MANAGER_REG02, 0xF8,
        ((coeff.pre_div - 1) << 5) | (coeff.pre_multi << 3));

    // REG03: fs_mode and adc_osr (full write OK)
    es8311_write_reg(ES8311_CLK_MANAGER_REG03,
        (coeff.fs_mode << 6) | coeff.adc_osr);

    // REG04: dac_osr
    es8311_write_reg(ES8311_CLK_MANAGER_REG04, coeff.dac_osr);

    // REG05: adc_div and dac_div
    es8311_write_reg(ES8311_CLK_MANAGER_REG05,
        ((coeff.adc_div - 1) << 4) | (coeff.dac_div - 1));

    // REG06: preserve bits [7:5] (BCLK invert etc), set bclk_div in [4:0]
    es8311_update_reg(ES8311_CLK_MANAGER_REG06, 0x1F, coeff.bclk_div - 1);

    // REG07: preserve bits [7:6], set lrck_h in [5:0]
    es8311_update_reg(ES8311_CLK_MANAGER_REG07, 0x3F, coeff.lrck_h);

    // REG08: lrck_l
    es8311_write_reg(ES8311_CLK_MANAGER_REG08, coeff.lrck_l);

    // SDP format: I2S slave, 16-bit
    // REG00: ensure slave mode (bit 6 = 0)
    es8311_update_reg(ES8311_RESET_REG00, 0x40, 0x00);

    // REG09 (SDP In / DAC): 16-bit I2S
    es8311_write_reg(ES8311_SDPIN_REG09, (3 << 2));

    // Disable ES8311 SDPOUT — it shares GPIO10 with ES7210 SDOUT1.
    // NOTE: CSM (REG00=0x80) auto-configures this register, so we set it
    // here AND re-force tri-state after CSM stabilizes (see below).
    es8311_write_reg(ES8311_SDPOUT_REG0A, 0x40);

    // Power up both DAC analog circuitry
    es8311_write_reg(ES8311_SYSTEM_REG0D, 0x01);
    es8311_write_reg(ES8311_SYSTEM_REG0E, 0x02);
    es8311_write_reg(ES8311_SYSTEM_REG12, 0x00);
    es8311_write_reg(ES8311_SYSTEM_REG13, 0x10);

    // Disable ES8311 ADC to ensure GPIO10 is free for ES7210
    es8311_write_reg(ES8311_SYSTEM_REG14, 0x00);  // Disable analog MIC input
    es8311_write_reg(ES8311_ADC_REG15, 0x00);     // ADC power off
    es8311_write_reg(ES8311_ADC_REG17, 0x00);
    es8311_write_reg(ES8311_ADC_REG16, 0x00);

    // ADC EQ bypass + cancel DC offset in digital domain (ESPHome writes this)
    es8311_write_reg(ES8311_ADC_REG1C, 0x6A);

    // DAC config
    es8311_write_reg(ES8311_DAC_REG37, 0x08);     // Bypass DAC equalizer

    // Set volume
    uint8_t vol = (currentVolume == 0) ? 0 : ((currentVolume * 256 / 100) - 1);
    es8311_write_reg(ES8311_DAC_REG32, vol);

    // Unmute DAC
    es8311_write_reg(ES8311_DAC_REG31, 0x00);

    // Power On — MUST be last, after all registers are configured.
    // CSM auto-configures some registers, so we configure everything first.
    es8311_write_reg(ES8311_RESET_REG00, 0x80);

    Serial.printf("ES8311: Codec initialized (vol=%d, reg32=0x%02X)\n", currentVolume, vol);

    // Force SDPOUT tri-state AFTER CSM has finished auto-configuring.
    // CSM (REG00=0x80) may override our earlier REG0A write.
    delay(50);
    es8311_write_reg(ES8311_SDPOUT_REG0A, 0x40);
    delay(5);
    uint8_t r0a = es8311_read_reg(ES8311_SDPOUT_REG0A);
    Serial.printf("ES8311: SDPOUT tristate: wrote 0x40, read 0x%02X\n", r0a);
    if (!(r0a & 0x40)) {
        Serial.println("ES8311: WARNING — CSM overrode tristate. Retrying write...");
        es8311_write_reg(ES8311_SDPOUT_REG0A, 0x40);
        delay(10);
        r0a = es8311_read_reg(ES8311_SDPOUT_REG0A);
        Serial.printf("ES8311: After retry: REG0A = 0x%02X (%s)\n",
                      r0a, (r0a & 0x40) ? "TRISTATE OK" : "STILL ACTIVE — may cause bus contention");
    } else {
        Serial.println("ES8311: SDPOUT tri-stated OK — GPIO10 free for ES7210");
    }

    es8311_dump_regs();
    return true;
}

void AudioHAL_init(void) {
    Serial.println("ESP32: Initializing Audio HAL...");

    init_pa_en();

    // Single I2S port: master, full-duplex (TX + RX on same peripheral)
    i2s_config_t i2sConfig = {};
    i2sConfig.mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_TX | I2S_MODE_RX);
    i2sConfig.sample_rate = SAMPLE_RATE;
    i2sConfig.bits_per_sample = I2S_BITS_PER_SAMPLE_32BIT;
    i2sConfig.channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT;
    i2sConfig.communication_format = I2S_COMM_FORMAT_STAND_I2S;
    i2sConfig.intr_alloc_flags = ESP_INTR_FLAG_LEVEL1;
    i2sConfig.dma_buf_count = 12;
    i2sConfig.dma_buf_len = 256;
    i2sConfig.use_apll = false;
    i2sConfig.tx_desc_auto_clear = true;
    i2sConfig.fixed_mclk = (int)MCLK_FREQ;

    esp_err_t err = i2s_driver_install(I2S_PORT, &i2sConfig, 0, NULL);
    if (err != ESP_OK) {
        Serial.printf("ESP32: I2S driver install failed: %s\n", esp_err_to_name(err));
        return;
    }

    i2s_pin_config_t pins = {};
    pins.mck_io_num = MCLK_PIN;
    pins.bck_io_num = BCLK_PIN;
    pins.ws_io_num = WS_PIN;
    pins.data_out_num = DOUT_PIN;
    pins.data_in_num = DIN_PIN;

    err = i2s_set_pin(I2S_PORT, &pins);
    if (err != ESP_OK) {
        Serial.printf("ESP32: I2S pin config failed: %s\n", esp_err_to_name(err));
        i2s_driver_uninstall(I2S_PORT);
        return;
    }

    i2s_zero_dma_buffer(I2S_PORT);

    Serial.println("ESP32: I2S started (full-duplex master on I2S0)");

    // Reduce drive strength on I2S clock outputs to minimize signal ringing
    gpio_set_drive_capability((gpio_num_t)MCLK_PIN, GPIO_DRIVE_CAP_1);
    gpio_set_drive_capability((gpio_num_t)BCLK_PIN, GPIO_DRIVE_CAP_1);
    gpio_set_drive_capability((gpio_num_t)WS_PIN, GPIO_DRIVE_CAP_1);
    gpio_set_drive_capability((gpio_num_t)DOUT_PIN, GPIO_DRIVE_CAP_1);

    delay(50);

    // ES7210 MCLK is on GPIO42 (confirmed by Waveshare BSP).
    // GPIO16 is NOT the MCLK pin — it's the MCP23017 I2C2_SDA.

    // Now init codecs with clocks already running
    if (!es8311_init_codec()) {
        Serial.println("ESP32: Audio init failed - no ES8311 codec found");
        return;
    }

    es7210_config_t es7210_cfg = ES7210_CONFIG_DEFAULT();
    es7210_cfg.mics = ES7210_MIC_ALL;
    es7210_cfg.gain = ES7210_GAIN_30DB;
    es7210_cfg.sample_rate = (es7210_sample_rate_t)SAMPLE_RATE;
    es7210_cfg.bits = ES7210_BITS_32;
    es7210_cfg.i2s_format = ES7210_I2S_NORMAL;
    es7210_cfg.enable_tdm = false;
    es7210_cfg.mclk_freq = MCLK_FREQ;

    if (ES7210_init(&es7210_cfg)) {
        es7210Present = true;
        Serial.println("ESP32: ES7210 microphone array initialized");
    } else {
        Serial.println("ESP32: ES7210 not found - using ES8311 ADC for mic");
    }

    // GPIO level test — AFTER codecs are initialized
    delay(100);
    {
        int highs = 0, lows = 0;
        for (int i = 0; i < 10000; i++) {
            if (gpio_get_level((gpio_num_t)DIN_PIN)) highs++; else lows++;
        }
        Serial.printf("ESP32: GPIO%d (DIN) level test: highs=%d lows=%d (%s)\n",
                      DIN_PIN, highs, lows,
                      (highs > 0 && lows > 0) ? "TOGGLING - data present!" :
                      (highs == 0) ? "STUCK LOW - no data on pin" : "STUCK HIGH");
    }

    audioInitialized = true;
    Serial.println("ESP32: Audio initialized successfully");
    Serial.printf("  Sample rate: %d Hz, 32-bit I2S\n", SAMPLE_RATE);
    Serial.printf("  MCLK: %d Hz on GPIO%d (via PLL_160M)\n", MCLK_FREQ, MCLK_PIN);
    Serial.printf("  I2S0 (full-duplex): BCLK=%d, WS=%d, DOUT=%d, DIN=%d\n",
                  BCLK_PIN, WS_PIN, DOUT_PIN, DIN_PIN);
    Serial.printf("  PA_EN: GPIO%d\n", PA_EN);
    Serial.printf("  ES8311: 0x%02X, ES7210: 0x%02X (%s)\n",
                  ES8311_I2C_ADDR, ES7210_I2C_ADDR,
                  es7210Present ? "active" : "not found");
}

void AudioHAL_start(void) {
    if (!audioInitialized) return;

    if (es7210Present) {
        ES7210_start();
    }

    delay(50);
    set_pa_enabled(true);

    audioRunning = true;
    Serial.println("ESP32: Audio started");
}

void AudioHAL_stop(void) {
    if (!audioInitialized) return;

    set_pa_enabled(false);
    delay(10);

    if (es7210Present) {
        ES7210_stop();
    }

    es8311_write_reg(ES8311_CLK_MANAGER_REG01, 0x00);
    es8311_write_reg(ES8311_RESET_REG00, 0x00);

    audioRunning = false;
    Serial.println("ESP32: Audio stopped");
}

void AudioHAL_setVolume(uint8_t volume) {
    if (!audioInitialized) return;
    if (volume > 100) volume = 100;
    currentVolume = volume;

    uint8_t vol = (volume == 0) ? 0 : ((volume * 256 / 100) - 1);
    es8311_write_reg(ES8311_DAC_REG32, vol);

    if (volume > 0) {
        es8311_write_reg(ES8311_DAC_REG31, 0x00);
    } else {
        es8311_write_reg(ES8311_DAC_REG31, 0x60);
    }
}

uint32_t AudioHAL_readMic(int16_t* buffer, uint32_t samples) {
    if (!audioInitialized || !audioRunning || !buffer) return 0;

    size_t bytesRead = 0;
    esp_err_t err = i2s_read(I2S_PORT, i2sDmaReadBuf, samples * sizeof(int32_t) * 2,
                             &bytesRead, 100 / portTICK_PERIOD_MS);
    if (err != ESP_OK) return 0;

    uint32_t frames = bytesRead / (sizeof(int32_t) * 2);

    // Convert 32-bit I2S slots to 16-bit: audio data is MSB-aligned
    for (uint32_t i = 0; i < frames * 2; i++) {
        buffer[i] = (int16_t)(i2sDmaReadBuf[i] >> 16);
    }

    return frames;
}

void AudioHAL_writeSpeaker(const int16_t* buffer, uint32_t samples) {
    if (!audioInitialized || !audioRunning || !buffer) return;

    // Convert 16-bit audio to 32-bit I2S slots: pack into MSB
    for (uint32_t i = 0; i < samples * 2; i++) {
        i2sDmaWriteBuf[i] = (int32_t)buffer[i] << 16;
    }

    size_t bytesWritten = 0;
    i2s_write(I2S_PORT, i2sDmaWriteBuf, samples * sizeof(int32_t) * 2,
              &bytesWritten, 100 / portTICK_PERIOD_MS);
}

bool AudioHAL_micAvailable(void) {
    return audioInitialized && (es7210Present || true);
}

bool AudioHAL_speakerReady(void) {
    return audioInitialized;
}

void AudioHAL_runDiagnostic(void) {
    Serial.println("\n========================================");
    Serial.println("    AUDIO PATH DIAGNOSTIC");
    Serial.println("========================================");

    // Kick-start TX DMA to ensure BCLK/WS are generating
    {
        int32_t zeros[64] = {};
        size_t written = 0;
        i2s_write(I2S_PORT, zeros, sizeof(zeros), &written, pdMS_TO_TICKS(50));
        delay(10);
    }

    // --- Test 1: MCLK on GPIO42 ---
    Serial.println("\n[TEST 1] MCLK on GPIO42:");
    {
        gpio_set_direction((gpio_num_t)MCLK_PIN, GPIO_MODE_INPUT_OUTPUT);
        esp_rom_gpio_connect_out_signal(MCLK_PIN, i2s_periph_signal[I2S_PORT].mck_out_sig, false, false);
        delayMicroseconds(50);
        int highs = 0, lows = 0;
        for (int i = 0; i < 10000; i++) {
            if (gpio_get_level((gpio_num_t)MCLK_PIN)) highs++; else lows++;
        }
        Serial.printf("  highs=%d lows=%d -> %s\n", highs, lows,
                      (highs > 1000 && lows > 1000) ? "MCLK PRESENT" : "NO MCLK");
    }

    // --- Test 2: ES8311 SDPOUT state ---
    Serial.println("\n[TEST 2] ES8311 SDPOUT (bus contention check):");
    {
        uint8_t r0a = es8311_read_reg(ES8311_SDPOUT_REG0A);
        Serial.printf("  REG0A = 0x%02X — bit6(tristate)=%d\n", r0a, (r0a >> 6) & 1);
        if (r0a & 0x40) {
            Serial.println("  -> SDPOUT tri-stated OK — GPIO10 free for ES7210");
        } else {
            Serial.println("  -> SDPOUT ACTIVE — ES8311 driving GPIO10!");
            Serial.println("     This causes bus contention with ES7210 SDOUT1");
        }
    }

    // --- Test 3: GPIO10 float detection ---
    Serial.println("\n[TEST 3] GPIO10 (I2S DIN) connection test:");
    {
        gpio_set_pull_mode((gpio_num_t)DIN_PIN, GPIO_PULLUP_ONLY);
        delay(1);
        int highs_pu = 0, lows_pu = 0;
        for (int i = 0; i < 1000; i++) {
            if (gpio_get_level((gpio_num_t)DIN_PIN)) highs_pu++; else lows_pu++;
        }

        gpio_set_pull_mode((gpio_num_t)DIN_PIN, GPIO_PULLDOWN_ONLY);
        delay(1);
        int highs_pd = 0, lows_pd = 0;
        for (int i = 0; i < 1000; i++) {
            if (gpio_get_level((gpio_num_t)DIN_PIN)) highs_pd++; else lows_pd++;
        }

        gpio_set_pull_mode((gpio_num_t)DIN_PIN, GPIO_FLOATING);

        Serial.printf("  Pull-UP:   highs=%d lows=%d\n", highs_pu, lows_pu);
        Serial.printf("  Pull-DOWN: highs=%d lows=%d\n", highs_pd, lows_pd);

        if (highs_pu > 100 && lows_pu > 100) {
            Serial.println("  -> TOGGLING: data present on the pin!");
        } else if (highs_pu > 900 && lows_pd > 900) {
            Serial.println("  -> FLOATING: nothing driving GPIO10");
        } else if (lows_pu > 900 && lows_pd > 900) {
            Serial.println("  -> DRIVEN LOW: connected but not outputting data");
        } else {
            Serial.printf("  -> UNEXPECTED\n");
        }
    }

    // --- Test 4: I2S RX data ---
    Serial.println("\n[TEST 4] I2S RX data (32-bit slots):");
    {
        int32_t buf32[256];
        size_t bytesRead = 0;
        i2s_read(I2S_PORT, buf32, sizeof(buf32), &bytesRead, pdMS_TO_TICKS(200));
        uint32_t sampleCount = bytesRead / sizeof(int32_t);
        int nonzero = 0;
        int16_t minVal = 0, maxVal = 0;
        for (uint32_t i = 0; i < sampleCount; i++) {
            int16_t s = (int16_t)(buf32[i] >> 16);
            if (s != 0) nonzero++;
            if (s < minVal) minVal = s;
            if (s > maxVal) maxVal = s;
        }
        Serial.printf("  bytes=%d samples=%d nonzero=%d range=[%d, %d]\n",
                      (int)bytesRead, (int)sampleCount, nonzero, minVal, maxVal);
        if (nonzero > 0) {
            Serial.printf("  First 16 (16-bit extracted): ");
            for (uint32_t i = 0; i < 16 && i < sampleCount; i++) {
                Serial.printf("%04X ", (uint16_t)(int16_t)(buf32[i] >> 16));
            }
            Serial.println();
            Serial.printf("  First 8 raw 32-bit: ");
            for (uint32_t i = 0; i < 8 && i < sampleCount; i++) {
                Serial.printf("%08X ", (unsigned int)buf32[i]);
            }
            Serial.println();
        }
    }

    // --- Test 5: BCLK and WS ---
    Serial.println("\n[TEST 5] BCLK/WS clocks:");
    {
        for (int pin : {BCLK_PIN, WS_PIN}) {
            int highs = 0, lows = 0;
            for (int i = 0; i < 10000; i++) {
                if (gpio_get_level((gpio_num_t)pin)) highs++; else lows++;
            }
            const char* name = (pin == BCLK_PIN) ? "BCLK" : "WS";
            Serial.printf("  %s (GPIO%d): highs=%d lows=%d -> %s\n",
                          name, pin, highs, lows,
                          (highs > 1000 && lows > 1000) ? "TOGGLING" : "NOT TOGGLING");
        }
    }

    // --- Test 6: ES7210 register state ---
    Serial.println("\n[TEST 6] ES7210 registers:");
    {
        Serial.printf("  REG00=0x%02X REG01=0x%02X REG06=0x%02X REG08=0x%02X\n",
                      ES7210_readReg(0x00), ES7210_readReg(0x01),
                      ES7210_readReg(0x06), ES7210_readReg(0x08));
        Serial.printf("  REG11=0x%02X REG12=0x%02X REG40=0x%02X\n",
                      ES7210_readReg(0x11), ES7210_readReg(0x12), ES7210_readReg(0x40));
        Serial.printf("  REG4B=0x%02X REG4C=0x%02X\n",
                      ES7210_readReg(0x4B), ES7210_readReg(0x4C));
    }

    // --- Test 7: GPIO matrix and I2S peripheral state ---
    Serial.println("\n[TEST 7] I2S peripheral & GPIO routing:");
    {
        int bck_sig = i2s_periph_signal[I2S_PORT].m_tx_bck_sig;
        int ws_sig = i2s_periph_signal[I2S_PORT].m_tx_ws_sig;
        int mck_sig = i2s_periph_signal[I2S_PORT].mck_out_sig;
        Serial.printf("  I2S TX signal IDs: MCLK=%d BCLK=%d WS=%d\n",
                      mck_sig, bck_sig, ws_sig);

        int rx_bck_sig = i2s_periph_signal[I2S_PORT].m_rx_bck_sig;
        int rx_ws_sig = i2s_periph_signal[I2S_PORT].m_rx_ws_sig;
        Serial.printf("  I2S RX signal IDs: BCLK=%d WS=%d\n", rx_bck_sig, rx_ws_sig);

        #define _GPIO_OUT_SEL(n) (GPIO_FUNC0_OUT_SEL_CFG_REG + (n) * 4)
        uint32_t mclk_func = REG_READ(_GPIO_OUT_SEL(MCLK_PIN)) & 0x1FF;
        uint32_t bclk_func = REG_READ(_GPIO_OUT_SEL(BCLK_PIN)) & 0x1FF;
        uint32_t ws_func = REG_READ(_GPIO_OUT_SEL(WS_PIN)) & 0x1FF;
        uint32_t dout_func = REG_READ(_GPIO_OUT_SEL(DOUT_PIN)) & 0x1FF;
        Serial.printf("  GPIO matrix OUT_SEL:\n");
        Serial.printf("    MCLK(GPIO%d)=%d %s\n", MCLK_PIN, mclk_func,
                      mclk_func == (uint32_t)mck_sig ? "MATCH" : "MISMATCH!");
        Serial.printf("    BCLK(GPIO%d)=%d %s\n", BCLK_PIN, bclk_func,
                      bclk_func == (uint32_t)bck_sig ? "MATCH" : "MISMATCH!");
        Serial.printf("    WS(GPIO%d)=%d %s\n", WS_PIN, ws_func,
                      ws_func == (uint32_t)ws_sig ? "MATCH" : "MISMATCH!");
        Serial.printf("    DOUT(GPIO%d)=%d\n", DOUT_PIN, dout_func);

        // Force reconnect BCLK/WS to TX I2S and re-test
        esp_rom_gpio_connect_out_signal(BCLK_PIN, bck_sig, false, false);
        esp_rom_gpio_connect_out_signal(WS_PIN, ws_sig, false, false);
        delay(10);

        int bclk_h = 0, bclk_l = 0, ws_h = 0, ws_l = 0;
        for (int i = 0; i < 10000; i++) {
            if (gpio_get_level((gpio_num_t)BCLK_PIN)) bclk_h++; else bclk_l++;
            if (gpio_get_level((gpio_num_t)WS_PIN)) ws_h++; else ws_l++;
        }
        Serial.printf("  After reconnect:\n");
        Serial.printf("    BCLK: highs=%d lows=%d -> %s\n", bclk_h, bclk_l,
                      (bclk_h > 1000 && bclk_l > 1000) ? "TOGGLING" : "NOT TOGGLING");
        Serial.printf("    WS:   highs=%d lows=%d -> %s\n", ws_h, ws_l,
                      (ws_h > 1000 && ws_l > 1000) ? "TOGGLING" : "NOT TOGGLING");
    }

    // Restore I2S pin routing after diagnostic GPIO tests
    {
        i2s_pin_config_t pins = {};
        pins.mck_io_num = MCLK_PIN;
        pins.bck_io_num = BCLK_PIN;
        pins.ws_io_num = WS_PIN;
        pins.data_out_num = DOUT_PIN;
        pins.data_in_num = DIN_PIN;
        i2s_set_pin(I2S_PORT, &pins);
    }

    Serial.println("\n========================================");
    Serial.println("    DIAGNOSTIC COMPLETE");
    Serial.println("========================================\n");
}

#endif // PLATFORM_ESP32
